### ISSUE TITLE
Error on linux when running script

### ISSUE THREAD

**Issue by Scalpweb** [FrostTheFox/ptc-acc-gen#22]
Hi,

When I'm running make_account.sh on my centos 7, I receive this error :

/home/creator/ptc-acc-gen/node_modules/nightmare/lib/nightmare.js:106
  this.queue((done) => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/creator/ptc-acc-gen/index.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

/home/creator/ptc-acc-gen/PogoPlayer/pogo.js:3
const pogobuf = require("pogobuf");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Find the generated accounts in PogoPlayer/accounts.csv

What should I do ?

**Comment by Scalpweb** [comment]
Well, I changed my nodejs version to latest. Now i get this :

  nightmare queuing process start +0ms
  nightmare queueing action "useragent" +4ms
Creating account 5001 of 6000
  nightmare queueing action "goto" for https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ +5ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +1ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +19ms
  nightmare electron child process not started yet, skipping kill. +1ms


I ran npm install again to be sure...

**Comment by johnkernke** [comment]
sounds like some of the issues i ran into, you might want to edit `makeaccounts.sh` and change the `DEBUG=` to `DEBUG=nightmare,electron:*` it will give you the reason why it wont run (it needs gtk and a bunch of other packages installed)

**Comment by pyr0ball** [comment]
Try running the npm install as root user:
`sudo npm install` 

If that fails, try installing that package specifically:
`sudo npm install electron`

**Comment by FrostTheFox** [comment]
Since this has become an electron problem. please use #24 for further discussion.

**Comment by tristaoeast** [comment]
@johnkernke running it with DEBUG=nightmare,electron:* made it work in VPS
