### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by KJFreakish** [FrostTheFox/ptc-acc-gen#26]
Running the latest version, but can't seem to get it going. I've done npm install and followed the instructions but no luck.
`fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
 
Error: ENOENT: no such file or directory, open 'C:\Users\KJ\Desktop\PGM\ptc-acc-
gen-master\node_modules\nightmare\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\Users\KJ\Desktop\PGM\ptc-acc-gen-master\node_modul
es\nightmare\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)`

**Comment by FrostTheFox** [comment]
Support's been dropped for this tool. Please use https://github.com/skvvv/pikapy.
