### ISSUE TITLE
error while running makeaccounts.sh [Debian]

### ISSUE THREAD

**Issue by Unyxos** [FrostTheFox/ptc-acc-gen#49]
Hi,

got this error while i'm trying to run the bot on Debian system : 

`root@server1:~/ptc-acc-gen# ./makeaccounts.sh
module.js:457
    throw err;
    ^

Error: Cannot find module 'nightmare'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/ptc-acc-gen/index.js:2:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
module.js:457
    throw err;
    ^

Error: Cannot find module 'pogobuf'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/ptc-acc-gen/PogoPlayer/pogo.js:3:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Find the generated accounts in PogoPlayer/accounts.csv`

**Comment by jnovack** [comment]
`npm install`

**Comment by FrostTheFox** [comment]
^

**Comment by FrostTheFox** [comment]
Closing for now, if issue persists please use the discord link in the readme.
