### ISSUE TITLE
Error: WARNING:  load timeout

### ISSUE THREAD

**Issue by Phantisy** [FrostTheFox/ptc-acc-gen#5]
debug(`WARNING:  load timeout of ${options.loadTimeout} is shorter than go
          ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pokemon/PokemonGo-Map/ptc-acc-gen/index.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by robjime** [comment]
Try updating your version of node, nodejs.

**Comment by swablueme** [comment]
@robjime Your solution worked
I ran these commands: http://tecadmin.net/upgrade-nodejs-via-npm/

**Comment by Phantisy** [comment]
What version would I need? I will have to manually compile it since I am currently using the latest version for Ubuntu 14..04 This is what I have now:
```
node -v
v0.10.25

```

**Comment by swablueme** [comment]
@Phantisy followed these steps: http://tecadmin.net/upgrade-nodejs-via-npm/ and it works fine unfortunately I get stuck on the creating '0 of x' accounts error

**Comment by Phantisy** [comment]
@swablueme I followed this "http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/" but now I get the same as you.

`~/PokemonGo-Map/ptc-acc-gen$ node index.js
Creating account 0 of 10
`
Then I am back at the prompt.

**Comment by swablueme** [comment]
@Phantisy
Seems like we all have the same issue: https://github.com/FrostTheFox/ptc-acc-gen/issues/6
It has been discussed on the discord too.
