### ISSUE TITLE
Error running on ubuntu

### ISSUE THREAD

**Issue by xcheneric** [FrostTheFox/ptc-acc-gen#59]
Hello, I'm having issues running this on my laptop. Runs fine on my desktop ubuntu though. 

Here's the error:

cheneric@SURFACE-6BBFBSB:~/ptc-acc-gen$ ./makeaccounts.sh
ptc-acc-gen v2.5.0 hotfix r1 by Sébastien Vercammen and Frost The Fox (and Github contribs)
Creating account 31 of 50
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './accounts.csv'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/cheneric/ptc-acc-gen/PogoPlayer/pogo.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
Find the generated accounts in PogoPlayer/accounts.csv

**Comment by xcheneric** [comment]
@teknicsrx7 I've tried that, but I get the same error.
