### ISSUE TITLE
ERROR: Error: Invalid response received from PTC login

### ISSUE THREAD

**Issue by rrbailey89** [FrostTheFox/ptc-acc-gen#61]
I always seem to get this error it seems that its almost always for 3 accounts no matter the amount of accounts. This error will repeat 3 times and then work but leave out 3 random accounts when assigning names. 

```
Failed to initialize client... ERROR: Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\pogobuf\pogobuf\pogobuf.ptclogin.js:108:28)
    at Request.self.callback (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (F:\Ray\Downloads\PoGoMap\ptc-acc-gen\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by FrostTheFox** [comment]
This is a pogoplayer issue, but try doing `npm update` just to make sure you have the latest pogobuf.

**Comment by FrostTheFox** [comment]
pogoplayer issue pls https://github.com/MRokas/PogoPlayer

**Comment by rrbailey89** [comment]
@FrostTheFox according to this discussion here https://github.com/cyraxx/pogobuf/issues/97 it was a username/pass issue. When using this script I chose to use a randomly generated password. I tried to manually login and discovered that the pass dumped in the accounts.csv file was incorrect. I was able to change the pass using the forgot password link within the game app and then was able to login. 

Is there any sort of info or any way I can run the script in a debug or other mode to help provide you with the information you need to track down the bug?

**Comment by xdemoor** [comment]
Same issue for me. Some accounts doesn't have the right password in accounts.csv.
