### ISSUE TITLE
Makeaccounts error

### ISSUE THREAD

**Issue by sapdkeybinder** [FrostTheFox/ptc-acc-gen#74]
./makeaccounts.sh
/test/ptc-acc-gen/config.js:33
useAutoCatcha: false,
^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/test/ptc-acc-gen/index.js:12:18)
    at Module._compile (module.js:556:32)
Auth service: ptc, Username: username1, Password: password1, Location: 00.00,00.00
Auth service: ptc, Username: username2, Password: password1, Location: 00.00,00.00
Failed to initialize client... ERROR: Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/test/ptc-acc-gen/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/test/ptc-acc-gen/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/test/ptc-acc-gen/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/test/ptc-acc-gen/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Failed to initialize client... ERROR: Error: Invalid response received from PTC login
    at Error (native)
    at Request.self.request [as _callback] (/test/ptc-acc-gen/node_modules/pogobuf/pogobuf/pogobuf.ptclogin.js:108:28)
    at Request.self.callback (/test/ptc-acc-gen/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/test/ptc-acc-gen/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/test/ptc-acc-gen/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Find the generated accounts in PogoPlayer/accounts.csv

**Comment by FrostTheFox** [comment]
can you please provide your full config.js (with sensitive info removed)?

**Comment by HelkaPL** [comment]
So, i have a similar error, at Linux server, when i try to use ptc-acc-gen i got something like that..
```
sh makeaccounts.sh
module.js:457
    throw err;
    ^

Error: Cannot find module 'nightmare'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/helkapl/PTCAcc/index.js:2:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
module.js:457
    throw err;
    ^

Error: Cannot find module 'pogobuf'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/helkapl/PTCAcc/PogoPlayer/pogo.js:3:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Find the generated accounts in PogoPlayer/accounts.csv

```
What I do wrong ?

**Comment by FrostTheFox** [comment]
@HelkaPL You need an `npm install` there.

**Comment by HelkaPL** [comment]
So, it's still not work... but after npm install (again)```
 sh makeaccounts.sh
/home/helkapl/PTCAcc/config.js:33
useAutoCatcha: false,
^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/helkapl/PTCAcc/index.js:12:18)
    at Module._compile (module.js:556:32)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './accounts.csv'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/home/helkapl/PTCAcc/PogoPlayer/pogo.js:6:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Find the generated accounts in PogoPlayer/accounts.csv

```
I'm sill ask for advice...

**Comment by nullpixel1** [comment]
I also get this issue

**Comment by vyruz1986** [comment]
Had the same issue, it was a comma missing at the end of the previous non-comment line (was country code in my case). Adding a comma after that line fixed it.

**Comment by HelkaPL** [comment]
@vyruz1986  Thanks a loot ;) It's solved that issue :) 

missing coma is in config.js file at line 30
```
// Country code (e.g. BE, FR, US, CA)
country:"PL", <-- there

// 2Captcha API key

```

**Comment by FrostTheFox** [comment]
@HelkaPL YES! I just thought that. I will have to address the config.py accordingly, thank you. I'll close this once it is resolved.

**Comment by FrostTheFox** [comment]
Please confirm that commit 114fe10 has fixed the issue.

**Comment by FrostTheFox** [comment]
Closing, latest commit fixed.
