### ISSUE TITLE
running make account.sh gives me this error

### ISSUE THREAD

**Issue by Wtcheesecakes** [FrostTheFox/ptc-acc-gen#80]
root@broadband:~/ptc-acc-gen# sh makeaccounts.sh

/root/ptc-acc-gen/node_modules/nightmare/lib/nightmare.js:94
    debug(`WARNING:  load timeout of ${options.loadTimeout} is shorter than go
          ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/ptc-acc-gen/index.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

/root/ptc-acc-gen/PogoPlayer/pogo.js:3
const pogobuf = require("pogobuf");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Find the generated accounts in PogoPlayer/accounts.csv
root@broadband:~/ptc-acc-gen#

**Comment by Spurlex** [comment]
You are using an outdated version of Node. Update node :)

**Comment by Wtcheesecakes** [comment]
okay ill try update

**Comment by FrostTheFox** [comment]
yeah, this issue is related to outdated node version.
