### ISSUE TITLE
Invalid Syntax error  

### ISSUE THREAD

**Issue by lueshi-me** [FrostTheFox/ptc-acc-gen#82]
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\USER\ptc-acc-gen\index.js:13:18)
    at Module._compile (module.js:556:32)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\USER\ptc-acc-gen\PogoPlayer\accounts.csv'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\Users\USER\ptc-acc-gen\PogoPlayer\pogo.js:6:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
"Find the generated accounts in PogoPlayer/accounts.csv"
Press any key to continue . . .

**Comment by Extrememist** [comment]
First of all `Error: ENOENT: no such file or directory, open 'C:\Users\USER\ptc-acc-gen\PogoPlayer\accounts.csv'` says that it cannot find that  file is there that file in there ?

**Comment by FrostTheFox** [comment]
^ please update

**Comment by lueshi-me** [comment]
Working on it
